### ISSUE TITLE
Swift3 API guideline update for enum cases

### ISSUE THREAD

**Issue by s** [nahitheper/SwiftColorPalette#2]
Hey,
Congrats for the awesome tool! I was just wondering if you should consider updating code generation to be consistent with latest Swift API guidelines as it's stated [here](https://github.com/apple/swift-evolution/blob/master/proposals/0006-apply-api-guidelines-to-the-standard-library.md) in subsection "Lowercase enum cases and static properties."

And I would do that myself but unfortunately have never dealt with cocoascripts before.
Best.

**Comment by nahitheper** [comment]
Thanks your great feedback Said.
I updated the code generation.
